### ISSUE TITLE
Enhance the user experience in configuring API Operator with Docker-Hub

### ISSUE THREAD

**Issue by dinusha92** [wso2/K8s-api-operator#184]
**Description:**

As of now, the configuration steps break the user experience. We need to enhance the UX to avoid the confusions for the users.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dinusha92** [comment]
I have tried different approaches. But in my opinion, they again create bad user experience.

1. Using a local HTTP registry.
This has been easy, and the image get pushed without any issue once an additional argument (--insecure) is passed to the Kaniko container. But, when creating pods, dockers images are pulled with HTTPS. Hence it is giving the following error in the pod.
```
Failed to pull image "reg-service:32000/online-store2:v1.0.0": rpc error: code = Unknown desc = Error response from daemon: Get https://reg-service:32000/v2/: http: server gave HTTP response to HTTPS client
```
I also created a seperate docker-secret for pulling and included that as "imagePullSecrets" in the pod template. But still the error continues to occur. 
In order to overcome this we need to configure this registry as a "insecure-registry" in the docker-daemons configs of each node in Kubernetes cluster.

2. Using a local HTTPS registry.

I created a key and a secret and attached it to the registry pod. Then the relevant cert is mounted to the Kaniko pod. After that, the flow worked fine upto image getting pushed to the registry.
But when pulling it gives the certificate issue and the cluster docker daemon does not possess the public certificate of the private registry. In order to do that, we need to log in to each node in the cluster and attach it manually.

Since both of the above approaches are not enhancing we may have to look for other options. Appreciate if you have any idea.

@lakwarus @pubudu538 Appreciate if you have any suggestions.

**Comment by renuka-fernando** [comment]
**Above changes:** updated the logic `isImageExist` to get credentials for docker-registry directly from the secret (`docker-config`) instead of the config-map (`docker-secret`).

Currently, the secret `docker-config` is created by the `api-controller` logic with using the config-map `docker-secret`. With above changes the CLI tool, `apictl` is responsible for creating the secret `docker-config`.
