### ISSUE TITLE
Issues in the quick start guide

### ISSUE THREAD

**Issue by bhathiya** [wso2/k8s-api-operator#195]
**Description:**

1. In the step 4, we're asked to "Download API controller v3.0.0 for your operating system from the website". But when we visit we don't see a download link to `API controller v3.0.0`. The link is for `Dev-Ops Tooling`. 

Maybe we can fix the QSG like this?

"Download Dev-Ops Tooling (API controller v3.0.0) for your operating system from the website".

or

"Download API controller v3.0.0 (Dev-Ops Tooling) for your operating system from the website".

2. Liveness and readiness probes start after 5 mins which is too long. Ideally, it should start early and have a retry mechanism until the pod is ready.

3. apictl readme says `For WSO2 API Manager 2.6.0`.

4. Mac doesn't trust the developer of apictl. 

5. In step 3, it says "For Docker for Mac use 'localhost' for the K8s node IP"

this should be `127.0.0.1` instead of `localhost`.

**Comment by pubudu538** [comment]
Hi,

Please find the answers to the above 5 issues.

1. Fixed
2. Startup probe will be introduced in the next release as it only available in K8s v1.16 version. For the moment we dont have any option other than liveness probe
3. Fixed
4. Should be fixed in apictl repo
5. Fixed

Thank you!

**Comment by bhathiya** [comment]
Please create an issue for 4.

**Comment by pubudu538** [comment]
Issue created in https://github.com/wso2/product-apim-tooling/issues/476
