### ISSUE TITLE
Disable authentication for API deployed in the Kubernetes cluster.

### ISSUE THREAD

**Issue by dinusha92** [wso2/K8s-api-operator#197]
**Description:**

As of now, if the API definition does not contain any security value, it will automaticcalu add the default security for the API. There is no way for a user to create an API without security so that the API can be accessed without an access token.

Hence APIM operator should be able to handle it and avoid applying security if the relevant property is present in API definition.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Shehanir** [comment]
By default the APIs and resources are protected via oauth2 in api-operator. API consumer need a valid oauth2 access token(jwt or opaque) to invoke the APIs. 
With new improvements API developer can expose APIs without any authentication using the open API extension **x-wso2-disable-security**.  Note that this extension is supported only at resource level. 

Example:

> paths:
  "/pet/findByStatus":
    get:
      tags:
      - pet
      summary: Finds Pets by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findPetsByStatus
      **x-wso2-disable-security: true**


After adding this extension to the swagger definition in resource level, API consumers can invoke APIs without any authentication as follows.

> curl -X GET "https://<External_IP>:9095/petstoreint/v1/pet/findByStatus?status=available"  -H "accept: application/xml"  -k

Output: 

> {
    "pets":[{"id":15435006003237, "photoUrls":[], "tags":[], "status":"available"}, {"id":3487237947289472730, "photoUrls":[], "tags":[], "status":"available"}], 
    "length":20509
}

**Comment by pubudu538** [comment]
So if we want to disable security for an API, then we need to add this extension "x-wso2-disable-security: true" in all the resources. I am resolving this issue as answered.
