### ISSUE TITLE
Support Ingress instead of LB type for the service

### ISSUE THREAD

**Issue by pubudu538** [wso2/k8s-api-operator#199]
**Description:**
At the moment, an API is exposed as a load balancer service type. We should be able to expose these using an ingress.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by patilpreetam** [comment]
Any update on this issue ?

**Comment by pubudu538** [comment]
Hi @patilpreetam,

We have already started on this effort and you can find the WIP PR related to this in [1]. The plan is to release this in the next release. We are hoping to do a release in 2, 3 weeks' time. 

[1] - https://github.com/wso2/K8s-api-operator/pull/207 

Thank you!
Pubudu.

**Comment by pubudu538** [comment]
Fixed with https://github.com/wso2/k8s-api-operator/pull/248 and https://github.com/wso2/k8s-api-operator/pull/249
