### ISSUE TITLE
Test API Operator with different container registries

### ISSUE THREAD

**Issue by dinusha92** [wso2/K8s-api-operator#200]
**Description:**

Currently, we have tested this with DockerHub.
We need to do the testing with following registries.

1. DockerHub (Already tested)  https://cloud.google.com/container-registry/
2. GCR : https://cloud.google.com/container-registry/
3. AWS ECR : https://aws.amazon.com/ecr/
4. Quary.io : https://quay.io/
5. Local registries (HTTP & HTTPS)

Please comment if you have more suggestions.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by pubudu538** [comment]
Fixed with https://github.com/wso2/K8s-api-operator/pull/209
