### ISSUE TITLE
Update the versions of k8s artifacts to be compatible with latest k8s versions

### ISSUE THREAD

**Issue by dinusha92** [wso2/k8s-api-operator#205]
**Description:**

k8s resources getting generated from the operator, needs to be updated to be compatible with latest k8s versions.
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dinusha92** [comment]
Since we use the minimum k8s version as 1.12, every k8s API in the API operator is up to date. 
But when we are moving to the higher version (for example 1.14 as the minimum support version), we will need to update autoscaling API for v2beta2 and the ingress for networking/v1beta1

**Comment by pubudu538** [comment]
I tested the API Operator Kubernetes v1.16 and I could notice the deployment version is set to apps/v1. But when tested in Kubernetes v1.14, it is set to extensions/v1beta1. Based on my observation, this is governed by the Kubernetes cluster itself.
