### ISSUE TITLE
Error overriding an API when the registry type is AWS ECR 

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/k8s-api-operator#279]
**Description:**
When overriding an API when the registry type is AWS ECR, the MGW runtime not uses the latest built image and the build image is untagged.
![image](https://user-images.githubusercontent.com/23183042/78034886-f8c92d80-7385-11ea-9c2c-6ab2b839ceea.png)

**Steps to reproduce:**
1. Install api-operator with reg type as AWS ECR
1. Add an API: `apictl add api -n petstore-int -f swagger.yaml`
1. Override the above API: `apictl add api -n petstore-int -f swagger2.yaml --override`

**Comment by pubudu538** [comment]
This is the behavior in AWS. New images will be available with the image tag. The old image is getting untagged.
