### ISSUE TITLE
Improve kubectl get api response

### ISSUE THREAD

**Issue by pubudu538** [wso2/k8s-api-operator#316]
**Description:**
Currently only api name and age is show. This can be improved to display multiple values such as ingress hostname, lb ip, replicas, etc.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dinusha92** [comment]
@Uvindu96 has done the implementation for this. He will be able to provide a sample response for better understanding.

**Comment by Uvindu96** [comment]
I have improved the command, Now this "apictl get api" command will show you the mode of the API, replica count, and endpoint. in default operator mode endpoint will be external-IP address and if the operator mode is ingress or route endpoint will be the relevant hostname.
![Screenshot from 2020-04-29 17-16-27](https://user-images.githubusercontent.com/31029812/83619029-eb5c3980-a5a8-11ea-82d0-e8b714bce650.png)
