### ISSUE TITLE
Refactor API Controller code

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/k8s-api-operator#326]
**Description:**
Currently API Controller file contains [2793 lines of code](https://github.com/wso2/k8s-api-operator/blob/v1.1.0/api-operator/pkg/controller/api/api_controller.go#L2793). Should be refactored.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by pubudu538** [comment]
This is fixed.
