### ISSUE TITLE
Issue in installation

### ISSUE THREAD

**Issue by LesterThomas** [wso2/k8s-api-operator#331]
**Description:**
I received the following error when following the installation guide on a brand-new aws eks cluster.
Executing the command:
apictl install api-operator
Using my docker.io repository, I received the error:

unable to recognize "https://github.com/wso2/k8s-api-operator/releases/download/v1.1.0/api-operator-configs.yaml": no matches for kind "Security" in version "wso2.com/v1alpha1"

I believe this was because kubernetes was trying to use the Security CRD before it had been created. I worked-around the issue by manually applying the Security CRD from the file api-operator-configs.yaml and then issuing the apictl install api-operator command again

**Affected Product Version:**
1.1.0

**OS, DB, other environment details and versions:**    
kubernetes v1.14.9-eks-502bfb on aws eks

**Steps to reproduce:**
Run installation instructions from https://github.com/wso2/k8s-api-operator

**Comment by pubudu538** [comment]
Hi,

We are extremely sorry that we have missed your issue. Did you resolve this issue?

You can try applying the Security CRD manually by using the kubectl command - https://github.com/wso2/k8s-api-operator/blob/v1.1.0/api-operator/deploy/crds/wso2_v1alpha1_security_crd.yaml

Then you can use the apictl install api-operator command.

Thank you!
Pubudu.

**Comment by LesterThomas** [comment]
Hi Pubudu, yes - applying the Security CRD manually first works for me. Many thank!

**Comment by renuka-fernando** [comment]
hi,

The fix will be available in API Controller (apictl) 3.2.0
