### ISSUE TITLE
Scenario for Shared Deployment Mode

### ISSUE THREAD

**Issue by dinusha92** [wso2/k8s-api-operator#335]
**Description:**

As of now, API Operator supports the main 3 deployment patterns.
1. private jet
2. side car
3. shared.

But to demonstrate the "shared" deployment pattern we don't have a intutive scenario available. However the same use case is available in different name in the scenario section.
"sample-16 deploy multiple swagger projects as a single API"

This has to be refactored to emphasise the "shared" deployment pattern. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by pubudu538** [comment]
Fixed with https://github.com/wso2/k8s-api-operator/pull/389
