### ISSUE TITLE
Cannot deploy 2 apis 

### ISSUE THREAD

**Issue by joaoemilio** [wso2/k8s-api-operator#341]
**Description:**
Can't deploy 2 apis 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
1.1.0

**OS, DB, other environment details and versions:**    
MacOS

**Steps to reproduce:**
try to deploy two scenarios one after another without deleting the first one

**Related Issues:**

**Comment by pubudu538** [comment]
You should have enough memory and cpu in your machine. Please describe the pending pods to check the root cause.

**Comment by joaoemilio** [comment]
I have tried both my mac running docker on desktop (7 CPUs and 12GB RAM) and AWS EKS - nodegroup with 2 nodes m5.large

**Comment by dinusha92** [comment]
Can you elaborate on this more? did you see kaniko pod running related to the 2nd API? Did the image get created and pushed to the configured docker repository? (etc)

**Comment by pubudu538** [comment]
We are unable to reproduce this. The scenario works fine - https://github.com/wso2/k8s-api-operator/tree/master/scenarios/scenario-16

Please reopen if you encounter any issue.
