### ISSUE TITLE
RateLimiting doesn't seem to work well

### ISSUE THREAD

**Issue by joaoemilio** [wso2/k8s-api-operator#344]
**Description:**
This is the policy I am creating
apiVersion: wso2.com/v1alpha1
kind: RateLimiting
metadata:
  name: quinhentosmilreqpolicy
spec:
  type: advance             
  description: Permite 500000 requests por minuto   # optional
  timeUnit: min
  unitTime: 1
  requestCount:
   limit: 500000

**This is the OpenAPI definition**
openapi: 3.0.0
info:
  title: DelayAPI
  version: 1.0.0
  description: This API contains operations related to online shopping store.
x-wso2-basePath: /delay/{version}
x-wso2-throttling-tier: quinhentosmilreqpolicy
x-wso2-production-endpoints:
  urls:
    - http://delay

paths:
  /versao:
    get:
      parameters:
        - name: x-delay
          in: header
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation

**K8s deployment for the microservice**
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  labels:
    app: "delay"
    version: "1.0.0"
  name: "delay"
spec:
  ports:
    - port: 80
      protocol: "TCP"
      targetPort: 9090
      name: "http"
  selector:
    app: "delay"
    version: "1.0.0"
  type: "LoadBalancer"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations: {}
  labels:
    version: "1.0.0"
    app: "delay"
  name: "delay-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      version: "1.0.0"
      app: "delay"
  template:
    metadata:
      annotations: {}
      labels:
        version: "1.0.0"
        app: "delay"
    spec:
      containers:
        - image: "joaoemilio/delay:1.0.0"
          imagePullPolicy: "Always"
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            tcpSocket:
              port: 9090
          name: "delay-deployment"
          ports:
            - containerPort: 9090
              protocol: "TCP"
      nodeSelector: {}

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
1.1.0 

**OS, DB, other environment details and versions:**    
AWS EKS - Kubernetes v1.15

**Steps to reproduce:**
I am using Jmeter to call the api without stop. Eventually it stops long before the 500k requests. 

**Related Issues:**

**Comment by dinusha92** [comment]
Hi @joaoemilio ,

Did you receive a throttled out message at this point?

**Comment by pubudu538** [comment]
We tested this use case for API Operator v1.2.0 and didn't encounter any issue. Hence closing this issue.
