### ISSUE TITLE
ImagePullSecret for Every registry types

### ISSUE THREAD

**Issue by dinusha92** [wso2/k8s-api-operator#353]
**Description:**

If private registries are used to keep the docker images of the APIs, the "imagePullSecret" has to be defined in the deployment definition.
But this seems to be not working for HTTPs private registries.
Hence this flow has to be checked and fix the issues for every registry type.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
1.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by renuka-fernando** [comment]
We are setting `ImagePullSecrets` in https://github.com/wso2/k8s-api-operator/blob/v1.1.0/api-operator/pkg/controller/api/api_controller.go#L1713
