### ISSUE TITLE
Error: unknown command "kubectl" for "kubectl"

### ISSUE THREAD

**Issue by LesterThomas** [wso2/k8s-api-operator#354]
I have deployed the ws02 api and operator on a new GKE cluster. I have followed scenario-1 and everything works correctly until I try and delete the API. When I issue the command `apictl delete api online-store` I get the error:
```
Error: unknown command "kubectl" for "kubectl"
```

 I'm using apictl 3.1.1

**Comment by LesterThomas** [comment]
I can delete the API using kubectl. The command `kubectl delete api online-store' worked (deleted the API CRD and the operator cleaned-up the deployments and services).

**Comment by dinusha92** [comment]
Hi @LesterThomas did you change the apictl mode to k8s?  " apictl set --mode k8s". Can you do this and try?

**Comment by dinusha92** [comment]
@LesterThomas I could reproduce this with 3.1.1 and 3.1.2.  It is working fine with 3.1.0. I missed that to state in previous comment as I was testing with 3.1.0. We'll have a look and get back to you on this.
Thanks for reporting the issue.
As you already have mentioned, please use the _**kubectl delete api**_ command meanwhile.

Thanks.

**Comment by renuka-fernando** [comment]
Hi @LesterThomas thanks for reporting this.

**Comment by npamudika** [comment]
This issue has been fixed in https://github.com/wso2/product-apim-tooling/releases/tag/v3.1.3
