### ISSUE TITLE
Possible security issue with the token in the README

### ISSUE THREAD

**Issue by wx-yz** [wso2/k8s-api-operator#355]
**Description:**
Went through the README file here to setup the operator - https://github.com/wso2/k8s-api-operator/blob/v1.1.0/README.md. During Step 6, token that's listed in the README worked for me when accessing the API.

Isn't this a potential security issue? Is there no life-time validate for JWTs?

**Comment by pubudu538** [comment]
This token only works for the default Keystore and we have generated a token in which the token expiry is infinite.

**Comment by wx-yz** [comment]
Thanks! Maybe it's good to have a note in the docs about this? I was taken by surprise when this worked like magic.
