### ISSUE TITLE
Kubernetes services are always of LoadBalancer Types

### ISSUE THREAD

**Issue by medkbadri** [wso2/k8s-api-operator#356]
**Description:**
When creating an api with apictl command, we always end up with LoadBalancer Kubernetes service

**Suggested Resolution:**
provide an option with apictl to specify the Kubernetes service type or the option to pass a config file for Kubernetes

**Why this is needed:**
In order to use an existing ingress controller

**Comment by medkbadri** [comment]
I just figured out how to do it by updating operatorMode!

**Comment by pubudu538** [comment]
Yes, you can change the operatorMode - https://github.com/wso2/k8s-api-operator/tree/master/scenarios/scenario-17
