### ISSUE TITLE
[Docs]Registry type listing under Reconfigure Registry is not distinctly visible 

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/k8s-api-operator#357]
**Description:**
The registry types listing under _Reconfigure Registry_[1] docs is not distinctly visible. It will be better to show the option to list registry types a bit more prominently so that it can be easily noticed.

<img width="1399" alt="Screenshot 2020-05-22 at 16 55 16" src="https://user-images.githubusercontent.com/20040505/82663799-fb415880-9c4d-11ea-9e5f-e992eafdfa87.png">

[1]. https://github.com/wso2/k8s-api-operator/blob/48bb41c1d4cb2557b425834868534ee6fb533c99/docs/HowToGuide/WorkingWithDockerRegistries/reconfigure-registry.md

**Comment by pubudu538** [comment]
Fixed with https://github.com/wso2/k8s-api-operator/pull/389
