### ISSUE TITLE
[Doc]Improve documentation on configuring MGW via APICTL

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/k8s-api-operator#358]
**Description:**
Improve the configuration overview documentation on configuring MGW via APICTL.

[1].  https://github.com/wso2/k8s-api-operator/blob/master/docs/HowToGuide/configurations-overview.md

**Comment by pubudu538** [comment]
Fixed with https://github.com/wso2/k8s-api-operator/pull/389
