### ISSUE TITLE
Pull docker images from a private docker registry secured with Basic Auth

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/k8s-api-operator#359]
**Description:**
Add support to pull docker images from a private docker registry that is secured with Basic Auth.

**Comment by dinusha92** [comment]
@renuka-fernando do we have any update on this?

**Comment by renuka-fernando** [comment]
I have tested this with creating a HTTP private docker registry secured with basic auth and pushing MGW toolkit and MGW runtime image into it. Configured the same registry to push images created by Kaniko job (MGW). It worked successfully.

**Comment by renuka-fernando** [comment]
In this version, we have not configured pull-secret for operator deployment. Hence, the operator docker image should be in a public registry (Docker Hub). I think we should handle this.
@pubudu538 WDT?

**Comment by renuka-fernando** [comment]
This is discussed in #338 and working for private registry both secured with basic auth and not secured with basic auth.
