### ISSUE TITLE
Check the possibility of importing all the swaggers via the apictl

### ISSUE THREAD

**Issue by pubudu538** [wso2/k8s-api-operator#423]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by renuka-fernando** [comment]
#### Tested with swagger definitions in following scenarios
- [x] Scenario 1
- [x] Scenario 2
- [x] Scenario 3
- [x] Scenario 4
- [x] Scenario 5
- [x] Scenario 6
- [x] Scenario 7
- [x] Scenario 8
- [x] Scenario 9
- [x] Scenario 10
- [ ] Scenario 11 - no swagger - Analytics scenario
- [x] Scenario 12
- [x] Scenario 13
  - [x] S01
  - [x] S02
  - [x] S03
- [x] Scenario 14
- [x] Scenario 15
- [x] Scenario 16
- [x] Scenario 17
- [x] Scenario 18
- [x] Scenario 19
- [x] Scenario 20
- [x] Scenario 21
- [x] Scenario 22
