### ISSUE TITLE
Support for Azure Docker Registry

### ISSUE THREAD

**Issue by pubudu538** [wso2/k8s-api-operator#434]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by renuka-fernando** [comment]
Get Access Token for Azure ACR : https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication#az-acr-login-with---expose-token

- Select "HTTPS Private Registry" as registry type
- Use <loginServer> as the repository name
- Username:  00000000-0000-0000-0000-000000000000
- Password: <accessToken>

#### Sample
##### Sample Access Token
```json
{
  "accessToken": "eyJhbGciOiJSUzI1NiIs[...]24V7wA",
  "loginServer": "myregistry.azurecr.io"
}
```

##### Install API Operator with ACR as registry type
```sh
$ apictl install api-operator
Choose registry type:
1: Docker Hub
2: Amazon ECR
3: GCR
4: HTTP Private Registry
5: HTTPS Private Registry
6: Quay.io
Choose a number: 1: 5
Enter repository: myregistry.azurecr.io
Enter username: 00000000-0000-0000-0000-000000000000
Enter password: <accessToken>
```

**Comment by RakhithaRR** [comment]
The approach mentioned in https://github.com/wso2/k8s-api-operator/issues/434#issuecomment-675393160 will allow the user to push and pull images from ACR. However, that token doesn't have enough permission to get the available list of tags for a repository in ACR (i.e. Kaniko job will run everytime even for existing APIs).

The approach in https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication#admin-account can be used to overcome this. We can use the username and password obtained from this when installing the operator.

```
$ apictl install api-operator
Choose registry type:
1: Docker Hub
2: Amazon ECR
3: GCR
4: HTTP Private Registry
5: HTTPS Private Registry
6: Quay.io
Choose a number: 1: 5
Enter repository: myregistry.azurecr.io
Enter username: <adminUsername>
Enter password: <adminPassword>
```

**Comment by pubudu538** [comment]
We will be closing this issue as there is a working solution.
