### ISSUE TITLE
Wrong security CRD used when multiple OpenAPI def with diferent security

### ISSUE THREAD

**Issue by McMlok** [wso2/k8s-api-operator#453]
**Description:**
I have API with two OpenAPI definitions. One is a JWT secured with a custom Key Manager defined as Security CRD from wso2.com. Another has disabled security with  the property x-wso2-disable-security: true. When I deploy API to K8s I can get response from unsecured API. But I'm not able to get response from secured one with JWT issued bz custom KM. But when I use JWT from samples I get response. If I look to Security CRD I see default-security-jwt resource in namespace where API is placed.

**Affected Product Version:**
K8s-Operator: 1.2.0
MGW-Toolkit: 3.2.0
MGW-Image: 3.2.0
Docker for Desktop: 2.3.0.4
Kubernets: 1.16.5

**Steps to reproduce:**
Use scenario-4 as template. But add another API with disabled security. Try call secured API with JWT signed with custom certificate.

[Yaml.zip](https://github.com/wso2/k8s-api-operator/files/5255134/Yaml.zip)

**Comment by pubudu538** [comment]
What is the values in the microgateway conf file? You can exec to the microgateway container and check this.

**Comment by RakhithaRR** [comment]
Hi @McMlok we have found an issue where the jwt issuers are being overridden when there are multiple swagger definitions with multiple issuers for the same API.
In your case, as a workaround, you can try by changing the order of the configmaps in your `api.yaml`.
i.e.
```
swaggerConfigmapNames:
      - weather-forecast-swagger
      - online-store-api-sc-1-swagger
```

**Comment by McMlok** [comment]
Thank you, workaround is working.
