### ISSUE TITLE
Ability to configure docker-registry-credentials item name and split pull and push secrets

### ISSUE THREAD

**Issue by McMlok** [wso2/k8s-api-operator#463]
**Description:**
We have our corporate private cloud with a managed K8s cluster and in every namespace, we provide secret with dockerconfigjson for our private HTTPS docker image repository, because we use it for every image pull. Will it be possible to configure this secret name to the API operator and not create special secret for the Operator? As I look to source code, now the name of secret is hard coded constant.

Will be also possible to split pull and push secrets and configure them? 

Thank you.

**Suggested Labels:**
Type/Improvement
Type/New Feature

**Affected Product Version:**
api-operator: 1.2.1
**OS, DB, other environment details and versions:**    
kubernetes: 1.15.3

**Comment by vassilvk** [comment]
@McMlok, until the operator author implements this (or if they decide not to), you can use a [KubeMod](https://github.com/kubemod/kubemod) ModRule to patch the objects generated by the operator and override the hardcoded secret with the name of your own.

**Comment by pubudu538** [comment]
This is added to v1.2.x
