### ISSUE TITLE
API Operator is mixing containers of several APIs when several APIs reconciled at the same time

### ISSUE THREAD

**Issue by pmartin-lvmh** [wso2/k8s-api-operator#468]
**Description:**

When the API Operator has to reconcile several APIs at the same time (for example when the API Operator pod restarts), it will add several containers to micro-gateways pods.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

k8s-api-operator 1.2.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

- Create 3 APIs in the same namespace, with some time between creations
- Wait for mgw pods to run 
- you get:
```
clientlists-api-cb4566dd7-prbpm    1/1     Running   0          5s
clients-api-79ff65b884-qppvj          1/1     Running   0          40s
users-api-6cc6477fd6-q85kh         1/1     Running   0          120s
```
- delete the operator pod and wait 
- you get:
```
clientlists-api-cb4566dd7-prbpm   1/3     CrashLoopBackOff    3          40s
clients-api-79ff65b884-qppvj         1/1     Running                     0          40s
users-api-6cc6477fd6-q85kh         1/2     CrashLoopBackOff   3          40s
```

I'm not sure to understand why you are managing a global list of containers in https://github.com/wso2/k8s-api-operator/blob/8ee6b0a0a65027f6a55955ac9bfbeffcca141a6b/api-operator/pkg/mgw/deployment.go#L53, but I think that you should pass the newly created container and not the complete list at: https://github.com/wso2/k8s-api-operator/blob/8ee6b0a0a65027f6a55955ac9bfbeffcca141a6b/api-operator/pkg/mgw/deployment.go#L196

**Related Issues:**

**Comment by renuka-fernando** [comment]
#### Related Issues:
https://github.com/wso2/k8s-api-operator/issues/461
