### ISSUE TITLE
Get variables from a secret for micro-gateway interceptor

### ISSUE THREAD

**Issue by pmartin-lvmh** [wso2/k8s-api-operator#470]
**Description:**

I'm adding an interceptor to a micro-gateway. I would need to get some value from a Kubernetes Secret to use by this interceptor.

At this time it is not possible to get values from a configmap or secret, but only define hard-coded environment variables with the `environmentVariables` field of the `APISpec`, or the `--env` flag of `apictl` .

It would be a nice-to-have to be able to also get variables from a secret.

**Comment by pubudu538** [comment]
Hi @pmartin-lvmh, 

We have this feature. Could you please try https://github.com/wso2/k8s-api-operator/tree/master/scenarios/scenario-23?

Let us know if this satisfies your requirement. We can do improvements to this feature.

Thank you!
Pubudu.

**Comment by pmartin-lvmh** [comment]
Hi @pubudu538 Yes, the 2nd approach is satisfactory for me. I can see two improvements for our developers and ops:

- being able to project the configmap / secret as environment variables also,
- being able to specify which configmap to use for a microgateway configs, and not always `mgw-deployment-configs`, so we can mount different configmaps/secrets for different APIs in the same namespace.

**Comment by pubudu538** [comment]
This is fixed with your contribution. Thank you for contributing to this.
