### ISSUE TITLE
Deploy APIs to Envoy Micro gateway Adapter

### ISSUE THREAD

**Issue by Jayanie** [wso2/k8s-api-operator#521]
**Description:**
- Should be able to deploy an API to Envoy Micro gateway Adapter component using API operator. 
- We can do this using a config map which either containing the zip file of an API project or swagger definition of an API.
In this case, kubectl will be used and recommended.

**Comment by renuka-fernando** [comment]
Duplicate of https://github.com/wso2/k8s-api-operator/issues/482
