### ISSUE TITLE
Remove unwanted watches....

### ISSUE THREAD

**Issue by pubudu538** [wso2/k8s-api-operator#533]
**Description:**

https://github.com/wso2/k8s-api-operator/blob/master/api-operator/pkg/controller/api/api_controller.go#L85

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by BLasan** [comment]
@pubudu538 will be working on this
