### ISSUE TITLE
api install operator failing 

### ISSUE THREAD

**Issue by saicharana731** [wso2/k8s-api-operator#559]
**Description:**
  trying to execute api install operator for k8 cluster is giving errors , im following references : https://github.com/wso2/k8s-api-operator/blob/master/docs/GettingStarted/quick-start-guide.md

![image](https://user-images.githubusercontent.com/49015023/108028117-4f4c6280-7051-11eb-8b0f-28f17b9eb217.png)

**Comment by saicharana731** [comment]
please find the log of it :

Resource: "apiextensions.k8s.io/v1beta1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition"
Name: "apis.wso2.com", Namespace: ""
for: "/tmp/example918665358/config-file-0.yml": CustomResourceDefinition.apiextensions.k8s.io "apis.wso2.com" is invalid: status.storedVersions[0]: Invalid value: "v1alpha2": must appear in spec.versions
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apiextensions.k8s.io/v1beta1\",\"kind\":\"CustomResourceDefinition\",\"metadata\":{\"annotations\":{},\"name\":\"targetendpoints.wso2.com\"},\"spec\":{\"group\":\"wso2.com\",\"names\":{\"kind\":\"TargetEndpoint\",\"listKind\":\"TargetEndpointList\",\"plural\":\"targetendpoints\",\"singular\":\"targetendpoint\"},\"scope\":\"Namespaced\",\"validation\":{\"openAPIV3Schema\":{\"description\":\"TargetEndpoint is the Schema for the targetendpoints API\",\"properties\":{\"apiVersion\":{\"description\":\"APIVersion defines the versioned schema of this representation of an object. Servers shouldconvert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources\",\"type\":\"string\"},\"kind\":{\"description\":\"Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds\",\"type\":\"string\"},\"metadata\":{\"type\":\"object\"},\"spec\":{\"description\":\"TargetEndpointSpec defines the desired state of TargetEndpoint\",\"properties\":{\"applicationProtocol\":{\"description\":\"Protocol of the application. Supports \\\"http\\\" and \\\"https\\\".\",\"type\":\"string\"},\"deploy\":{\"description\":\"Deployment details.\",\"properties\":{\"cpuLimit\":{\"type\":\"string\"},\"dockerImage\":{\"type\":\"string\"},\"maxReplicas\":{\"format\":\"int32\",\"type\":\"integer\"},\"memoryLimit\":{\"type\":\"string\"},\"minReplicas\":{\"format\":\"int32\",\"type\":\"integer\"},\"name\":{\"type\":\"string\"},\"reqMemory\":{\"type\":\"string\"},\"requestCPU\":{\"type\":\"string\"}},\"required\":[\"dockerImage\",\"name\"],\"type\":\"object\"},\"mode\":{\"description\":\"Mode of the Target Endpoint. Supports \\\"privateJet\\\", \\\"sidecar\\\", \\\"serverless\\\". Default value \\\"privateJet\\\"\",\"type\":\"string\"},\"ports\":{\"description\":\"List of optional ports of the target endpoint. First port should be the port of the target endpoint which is referred in swagger definition.\",\"items\":{\"description\":\"Port represents ports of the Target Endpoint\",\"properties\":{\"name\":{\"description\":\"The name of this port within the service. This must be a DNS_LABEL. All ports within a ServiceSpec must have unique names.\",\"type\":\"string\"},\"port\":{\"description\":\"The port that will be exposed by this service.\",\"format\":\"int32\",\"type\":\"integer\"},\"targetPort\":{\"description\":\"Port that is targeted to expose.\",\"format\":\"int32\",\"type\":\"integer\"}},\"required\":[\"name\",\"port\",\"targetPort\"],\"type\":\"object\"},\"type\":\"array\"}},\"required\":[\"applicationProtocol\",\"deploy\",\"ports\"],\"type\":\"object\"},\"status\":{\"description\":\"TargetEndpointStatus defines the observed state of TargetEndpoint\",\"type\":\"object\"}},\"type\":\"object\"}},\"version\":\"v1alpha1\",\"versions\":[{\"name\":\"v1alpha1\",\"served\":true,\"storage\":true}]}}\n"}},"spec":{"version":"v1alpha1","versions":[{"name":"v1alpha1","served":true,"storage":true}]}}
to:
Resource: "apiextensions.k8s.io/v1beta1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition"
Name: "targetendpoints.wso2.com", Namespace: ""
for: "/tmp/example918665358/config-file-3.yml": CustomResourceDefinition.apiextensions.k8s.io "targetendpoints.wso2.com" is invalid: status.storedVersions[0]: Invalid value: "v1alpha2": must appear in spec.versions
apictl: Error applying CRDs to K8s cluster Reason: exit status 1
Exit status 1

**Comment by saicharana731** [comment]
@dinusha92 @pubudu538 could you please help me out with this

**Comment by pubudu538** [comment]
Are you running on Openshift? What is the K8s version?

**Comment by saicharana731** [comment]
its on k8 (EKS)with below versions 
![image](https://user-images.githubusercontent.com/49015023/108159920-08707280-710e-11eb-8d4b-853b1a2682c2.png)

**Comment by pubudu538** [comment]
You have only listed the client version. Can we get the server version as well? I guess kubectl version command output is enough. We have tested the API Operator in K8s v1.19. I feel like you are trying this in v1.20.

**Comment by saicharana731** [comment]
![image](https://user-images.githubusercontent.com/49015023/108164161-47a2c180-7116-11eb-83d0-3e2faffa265f.png)

**Comment by BLasan** [comment]
> ![image](https://user-images.githubusercontent.com/49015023/108164161-47a2c180-7116-11eb-83d0-3e2faffa265f.png)
> 
> yes its v1.20 ,

server version is 1.18.9 right? I've tried the same scenario in minikube using the kubernetes server version 1.20.2. I was not getting any issues. Can you try uninstalling the api-operator and re-installing again?  Run 'apictl uninstall api-operator` . And  check whether any resources will be remained after uninstalling the api-operator. 'kubectl get all -n wso2-system`

**Comment by saicharana731** [comment]
sorry late response , was advised to move to micro-gw instead of apictl . Thanks for response
