### ISSUE TITLE
WSO2 API Operator to support the configuration of imagePullPolicy

### ISSUE THREAD

**Issue by Hashini-Deshappriya** [wso2/k8s-api-operator#617]
**Description:**
According to the integration_deployment.go file in the Github repository[1] the ImagePullPolicy has been hardcoded to PullAlways.

However, for development, the customer might already have images built locally. The customer believes it is easy to use the local images rather than pulling it again from a remote private repository. They require flexibility to set the imagePullPolicy to 'Never'/'IfNotPresent'. Hence we can added this as an improvement to the Operator.

[1] - https://github.com/wso2/k8s-api-operator/blob/master/api-operator/pkg/controller/integration/integration_deployment.go#L126

**Product** : MI 4.0.0
**Update level** :
**WSO2 case id** : UNIEXETERSUB-132
**Case number** : CS0185862
**SN Link**: https://wso2.service-now.com/now/workspace/agent/record/sn_customerservice_case/dcc1de27477b8d508d397834846d4354

**Comment by malakaganga** [comment]
Fixed with: https://github.com/wso2/k8s-api-operator/pull/613
